// A property of a type holds a value of that type: what it is given is made
// into one as Qt makes it, and what cannot be is refused. The answers are
// Qt's own, from the same scene run by `qml6`.
import { expect, open, test } from "./open.js";

const QT = [
  "number:2 | number:-2 | number:12 | number:3 | number:-64771072 | string:2.7 | string:3 | boolean:true | number:2.5 | number:1 | object:#ff0000 | object:#000000 | boolean:false | number:2.7 | number:0 | object:#000000",
  "int Error: Cannot assign QString to int number:2",
  "int number:0",
  "int Error: Cannot assign [undefined] to int number:0",
  "int Error: Cannot assign std::nullptr_t to int number:0",
  "int number:2",
  "int number:3",
  "int number:0",
  "int Error: Cannot assign QString to int number:0",
  "int number:7",
  "int Error: Cannot assign QJSValue to int number:7",
  "int Error: Cannot assign QJSValue to int number:7",
  "int number:3",
  "int number:100",
  "int Error: Cannot assign QString to int number:100",
  "int number:5",
  "int number:-3",
  "int Error: Cannot assign QString to int number:-3",
  "int number:12",
  "int number:1",
  "int number:5",
  "int number:0",
  "int number:-2147483648",
  "int number:2147483647",
  "int number:1",
  "int number:1",
  "int Error: Cannot assign QColor to int number:1",
  "int Error: Cannot assign QObject* to int number:1",
  "real number:NaN",
  "real Error: Cannot assign [undefined] to double number:NaN",
  "real number:0",
  "real number:1",
  "real number:7",
  "real number:16",
  "real number:0",
  "real number:NaN",
  "real number:NaN",
  "real number:0",
  "real number:3",
  "real number:NaN",
  "real number:NaN",
  "bool Error: Cannot assign [undefined] to bool boolean:true",
  "bool boolean:false",
  "bool boolean:true",
  "bool boolean:false",
  "bool boolean:true",
  "bool boolean:false",
  "bool boolean:false",
  "string Error: Cannot assign QJSValue to QString string:2.7",
  "string string:1e+21",
  "string string:0.30000000000000004",
  "string Error: Cannot assign QObject* to QString string:0.30000000000000004",
  "string string:red",
  "string string:#ff0000",
  "string string:",
  "string string:a",
  "string string:\u0001\u0002",
  "string string:Ab\u20ac\u0001",
  "string Error: Cannot assign JavaScript function to QString string:Ab\u20ac\u0001",
  "string string:0.3333333333333333",
  "string string:0",
  "string string:1e-07",
  "string string:1e-04",
  "string string:0.00015",
  "string string:0.001",
  "string string:1e-05",
  "string string:123456.789",
  "string string:1e+15",
  "string string:1e+10",
  "string string:1.5e+10",
  "string string:123456789012",
  "string string:9007199254740992",
  "string string:nan",
  "string string:inf",
  "string string:-inf",
  "string string:#80ff0000",
  "string string:100",
  "string string:true",
  "string string:",
  "string Error: Cannot assign [undefined] to QString string:",
  "text string:5",
  "text string:1.5",
  "text string:true",
  "text Error: Cannot assign [undefined] to QString string:true",
  "text string:",
  "text string:1e-07",
  "color object:#ff0000",
  "color object:#80ff0000",
  "color object:#00000000",
  "color object:#000000",
  "color object:#000000",
  "color object:#00ff00",
  "color object:#000000",
  "color object:#000000",
  "color object:#aabbcc",
  "color object:#000000",
  "color Error: Cannot assign [undefined] to QColor object:#000000",
  "text color object:#0000ff",
  "text color Error: Cannot assign [undefined] to QColor object:#0000ff",
  "text color object:#000000",
  "number:1 | number:-3 | number:2",
];

test("a typed property holds what Qt would have it hold", async ({ page }) => {
  await open(page, "typed");
  expect(await page.evaluate(() => window.scene.read())).toEqual(QT);
});
